export const validTypes = [
	{
		type: "feat",
		label: "Features",
		description: "A new feature",
		category: "features" as const,
		emoji: "🚀",
		badgeColor: "00D4AA",
		breakingAllowed: true,
	},
	{
		type: "fix",
		label: "Bug Fixes",
		description: "A bug fix",
		category: "bugfixes" as const,
		emoji: "🐛",
		badgeColor: "EF4444",
		breakingAllowed: true,
	},
	{
		type: "docs",
		label: "Documentation",
		description: "Documentation only changes",
		category: "documentation" as const,
		emoji: "📚",
		badgeColor: "646CFF",
		breakingAllowed: false,
	},
	{
		type: "style",
		label: "Style",
		description: "Changes that do not affect the meaning of the code",
		category: "refactoring" as const,
		emoji: "🎨",
		badgeColor: "8B5CF6",
		breakingAllowed: false,
	},
	{
		type: "refactor",
		label: "Refactoring",
		description: "A code change that neither fixes a bug nor adds a feature",
		category: "refactoring" as const,
		emoji: "🔧",
		badgeColor: "007ACC",
		breakingAllowed: true,
	},
	{
		type: "perf",
		label: "Performance",
		description: "A code change that improves performance",
		category: "refactoring" as const,
		emoji: "⚡",
		badgeColor: "60a5fa",
		breakingAllowed: true,
	},
	{
		type: "test",
		label: "Testing",
		description: "Adding missing tests or correcting existing tests",
		category: "infrastructure" as const,
		emoji: "🧪",
		badgeColor: "10B981",
		breakingAllowed: false,
	},
	{
		type: "ci",
		label: "CI/CD",
		description: "Changes to CI configuration files and scripts",
		category: "infrastructure" as const,
		emoji: "👷",
		badgeColor: "2496ED",
		breakingAllowed: false,
	},
	{
		type: "chore",
		label: "Chores",
		description: "Other changes that don't modify src or test files",
		category: "other" as const,
		emoji: "🔨",
		badgeColor: "495057",
		breakingAllowed: false,
	},
	{
		type: "revert",
		label: "Revert",
		description: "Reverts a previous commit",
		category: "other" as const,
		emoji: "⏪",
		badgeColor: "DC2626",
		breakingAllowed: true,
	},
	{
		type: "merge",
		label: "Merge",
		description: "Merge commits (pull requests, branches)",
		category: "other" as const,
		emoji: "🔀",
		badgeColor: "6B7280",
		breakingAllowed: false,
	},
	{
		type: "deps",
		label: "Dependencies",
		description: "Dependency updates and changes",
		category: "dependencies" as const,
		emoji: "📦",
		badgeColor: "059669",
		breakingAllowed: true,
	},
	{
		type: "other",
		label: "Other",
		description: "Other types of changes",
		category: "other" as const,
		emoji: "⚠️",
		badgeColor: "6B7280",
		breakingAllowed: false,
	},
] as const;
