FROM oven/bun:1.2.21-alpine AS base

RUN apk add --no-cache curl

WORKDIR /app

RUN addgroup --system --gid 1001 runner-group && adduser --system --uid 1001 runner-user
COPY --chown=runner-user:runner-group . .

RUN --mount=type=cache,target=/root/.bun/install/cache \
    --mount=type=cache,target=/app/node_modules/.cache \
    bun install
RUN --mount=type=cache,target=/app/.turbo \
    mkdir -p .turbo/cache && \
    chmod -R 777 .turbo
    
CMD ["sleep", "infinity"] 