FROM oven/bun:1.2.19 AS base

RUN bun install -g turbo@2.5.4

WORKDIR /app

COPY apps/ ./apps/
COPY packages/ ./packages/
COPY scripts/ ./scripts/
COPY package.json ./package.json
COPY bun.lock ./bun.lock

RUN bun install
