FROM oven/bun:1.2.19-alpine AS base

RUN apk add --no-cache curl

WORKDIR /app

COPY --chown=vscode-user:vscode-user . .

RUN --mount=type=cache,target=/root/.bun/install/cache \
    --mount=type=cache,target=/app/node_modules/.cache \
    bun install
RUN --mount=type=cache,target=/app/.turbo \
    mkdir -p .turbo/cache && \
    chmod -R 777 .turbo
    
CMD ["sleep", "infinity"] 